config/routes.rb
Rails.application.routes.draw do
  get 'rooms/index'

  get 'rooms/index'

  get 'access/index'

  get 'access/login'
post "rooms/new"
  resources :users #, :rooms do
  resources :rooms, :only =>[:new,:create]

 match '/rooms' => 'rooms#new',:via => [:get,:post]
 match '/rooms' => 'rooms#show',:via => [:get,:post]
 match '/access' => 'access#index',:via =>[:get,:post]
 resources :rooms do
  collection do
    get 'showall'
  end
end
  patch "access/updateprofile" => "access#updateprofile", :as => "access/updateprofile"

  root 'access#login'
  get 'user', :to =>"access#index"
  match ':controller(/:action(/:id))',:via => [:get,:post]

end

app/models/room.rb
class Room < ActiveRecord::Base
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def index
  	@room=Roomadd.all
  end
  def show
@room = Roomadd.find(params[:id])
  end

def new
	@room=Roomadd.new
	end
def edit
@room = Roomadd.find(params[:id])
@room.destroy
end
	def create
		@room=Roomadd.new(room_params)
		if @room.save
			redirect_to rooms_index_path
		else
			render 'new'
	end
end
def update
	@room=Roomadd.find(params[:id])
	temp = @room.update(room_params)
	temp.destroy
	if(temp)
		redirect_to @room
	else
		render 'edit'
	end
end


	def destroy
@room =Roomadd.find(params[:id])
@room.destroy
@roomno=@room.room_no
Booking.where(:roomnum => @roomno).delete_all
redirect_to rooms_index_path
	end
	private 
	def room_params
	params.require(:roomadd).permit(:room_no, :size, :location)

end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/edit.html.erb
<div id="header">
  <p>Library System</p>
  <div class="buttons">
    <button class="button"><%= link_to "Logout", :controller => 'Access', :action => 'login' %></button>
  </div>
  </div>
<div id="sidebar">


  <ul>
    <li class="category"><%= link_to "Home", :controller => 'access',  :action => 'roomadmin' %></li>
    <li class="category"><%= link_to "Profile", :controller => 'access', :action => 'userprofile' %></li>
    <li class="category"><%= link_to "Add Admin", :controller => 'access', :action => 'addadmin' %></li>
    <li class="category"><%= link_to "Manage Admins", :controller => 'access', :action => 'manageadmin' %></li>
    <li class="category"><%= link_to "Manage Members", :controller => 'access', :action => 'viewmembers' %></li>
    <li class="category"><%= link_to "Add Room", :controller => 'rooms', :action => 'new' %></li>
    <li class="category"><%= link_to "Manage Rooms", :controller => 'rooms', :action => 'index' %></li>
    <li class="category"><%= link_to "View/Delete Reservations", :controller => 'access', :action => 'viewallbooking' %></li>
    <li class="category"><%= link_to "View Future Schedule For Rooms", :controller => 'access', :action => 'viewroomfutureschedule' %></li>
    <li class="category"><%= link_to "View Reservations History For Rooms", :controller => 'access', :action => 'viewroombookinghistory' %></li>
    <li class="category"><%= link_to "View Reservations By Users", :controller => 'access', :action => 'viewuserbooking' %></li>
    <li class="category"><%= link_to "Create Reservations", :controller => 'access', :action => 'admincreatebooking' %></li>
  </ul>
</div>
<div style="margin:5% 5%;">

<h1>Edit Room Details</h1>
<%= form_for :roomadd, url:rooms_path(@room) do |f| %>
<h3>
<p>
Room No: <%= f.text_field :room_no %>
</p>
<p>
Size: <%= f.select :size, [['Small','4'],['Medium','6'],['Large','12']] %>
  </p>
<p>
Location: <%= f.select :location, ['DHHILL','Hunt'] %>
</p>
<p>
	<%= f.submit "Update"%>
</p>
<% end %>
</h3>
  </div>

app/views/rooms/index.html.erb

  <div id="header">
    <p>Library System</p>
    <div class="buttons">
      <button class="button"><%= link_to "Logout", :controller => 'Access', :action => 'login' %></button>
    </div>
  </div>

<div id="sidebar">

  <ul>
    <li class="category"><%= link_to "Home", :controller => 'access',  :action => 'roomadmin' %></li>
    <li class="category"><%= link_to "Profile", :controller => 'access', :action => 'userprofile' %></li>
    <li class="category"><%= link_to "Add Admin", :controller => 'access', :action => 'addadmin' %></li>
    <li class="category"><%= link_to "Manage Admins", :controller => 'access', :action => 'manageadmin' %></li>
    <li class="category"><%= link_to "Manage Members", :controller => 'access', :action => 'viewmembers' %></li>
    <li class="category"><%= link_to "Add Room", :controller => 'rooms', :action => 'new' %></li>
    <li class="category"><%= link_to "Manage Rooms", :controller => 'rooms', :action => 'index' %></li>
    <li class="category"><%= link_to "View/Delete Reservations", :controller => 'access', :action => 'viewallbooking' %></li>
    <li class="category"><%= link_to "View Future Schedule For Rooms", :controller => 'access', :action => 'viewroomfutureschedule' %></li>
    <li class="category"><%= link_to "View Reservations History For Rooms", :controller => 'access', :action => 'viewroombookinghistory' %></li>
    <li class="category"><%= link_to "View Reservations By Users", :controller => 'access', :action => 'viewuserbooking' %></li>
    <li class="category"><%= link_to "Create Reservations", :controller => 'access', :action => 'admincreatebooking' %></li>
  </ul>
</div>
<body>
<div style="margin:5% 5%;">

<h1>List Of All Rooms:</h1>
	<table style="width:100%; font-size: larger;">
		<tr>
			<th> Room number</th>
			<th>Size</th>
			<th>Location</th>
		</tr>

		<% @room.each do |roomadd| %>
		<tr>
			<td><%= roomadd.room_no %></td>
			<td><%= roomadd.size %> chairs</td>
			<td><%= roomadd.location %></td>
			<td><u><%= link_to 'Show', room_path(roomadd)%></u></td>
						<td><u><%= link_to 'Edit', edit_room_path(roomadd)%></u></td>
			<td><u><%= link_to 'Delete', room_path(roomadd), method: :delete%></u></td>
				</tr>
		<% end %>
	</table>
  </div>
</body>

app/views/rooms/new.html.erb
  <div id="header">
    <p>Library System</p>
    <div class="buttons">
      <button class="button"><%= link_to "Logout", :controller => 'Access', :action => 'login' %></button>
    </div>
  </div>
<div id="sidebar">

  <ul>
    <li class="category"><%= link_to "Home", :controller => 'access',  :action => 'roomadmin' %></li>
    <li class="category"><%= link_to "Profile", :controller => 'access', :action => 'userprofile' %></li>
    <li class="category"><%= link_to "Add Admin", :controller => 'access', :action => 'addadmin' %></li>
    <li class="category"><%= link_to "Manage Admins", :controller => 'access', :action => 'manageadmin' %></li>
    <li class="category"><%= link_to "Manage Members", :controller => 'access', :action => 'viewmembers' %></li>
    <li class="category"><%= link_to "Add Room", :controller => 'rooms', :action => 'new' %></li>
    <li class="category"><%= link_to "Manage Rooms", :controller => 'rooms', :action => 'index' %></li>
    <li class="category"><%= link_to "View/Delete Reservations", :controller => 'access', :action => 'viewallbooking' %></li>
    <li class="category"><%= link_to "View Future Schedule For Rooms", :controller => 'access', :action => 'viewroomfutureschedule' %></li>
    <li class="category"><%= link_to "View Reservations History For Rooms", :controller => 'access', :action => 'viewroombookinghistory' %></li>
    <li class="category"><%= link_to "View Reservations By Users", :controller => 'access', :action => 'viewuserbooking' %></li>
    <li class="category"><%= link_to "Create Reservations", :controller => 'access', :action => 'admincreatebooking' %></li>
  </ul>
</div>
  <div style="margin:5% 5%;">

  <h1>Add a New Room</h1>
<%= form_for :roomadd, url:rooms_path do |f| %>
<h3>
<p>
Room No: <%= f.text_field :room_no %>
</p>
<p>
Size:	<%= f.select :size, [['Small','4'],['Medium','6'],['Large','12']] %>
</p>
<p>
Location:	<%= f.select :location, ['DHHILL','Hunt'] %>
</p>
<p>
	<%= f.submit "Create Room" %>
</p>
</h3>
<% end %>
    </div>

app/views/rooms/show.html.erb
  <div id="header">
    <p>Library System</p>
    <div class="buttons">
      <button class="button"><%= link_to "Logout", :controller => 'Access', :action => 'login' %></button>
    </div>
  </div>
<div id="sidebar">


  <ul>
    <li class="category"><%= link_to "Home", :controller => 'access',  :action => 'roomadmin' %></li>
    <li class="category"><%= link_to "Profile", :controller => 'access', :action => 'userprofile' %></li>
    <li class="category"><%= link_to "Add Admin", :controller => 'access', :action => 'addadmin' %></li>
    <li class="category"><%= link_to "Manage Admins", :controller => 'access', :action => 'manageadmin' %></li>
    <li class="category"><%= link_to "Manage Members", :controller => 'access', :action => 'viewmembers' %></li>
    <li class="category"><%= link_to "Add Room", :controller => 'rooms', :action => 'new' %></li>
    <li class="category"><%= link_to "Manage Rooms", :controller => 'rooms', :action => 'index' %></li>
    <li class="category"><%= link_to "View/Delete Reservations", :controller => 'access', :action => 'viewallbooking' %></li>
    <li class="category"><%= link_to "View Future Schedule For Rooms", :controller => 'access', :action => 'viewroomfutureschedule' %></li>
    <li class="category"><%= link_to "View Reservations History For Rooms", :controller => 'access', :action => 'viewroombookinghistory' %></li>
    <li class="category"><%= link_to "View Reservations By Users", :controller => 'access', :action => 'viewuserbooking' %></li>
    <li class="category"><%= link_to "Create Reservations", :controller => 'access', :action => 'admincreatebooking' %></li>
  </ul>
</div>
  <div style="margin:5% 5%;">
<h1>Room Details</h1>
<h3>
    <p>
	<strong>Room number:</strong>
<%= @room.room_no %>
</p>
<p>
	<strong>Room Size:</strong>
<%= @room.size %>
</p>
<p>
	<strong>Location:</strong>
<%= @room.location %>
</p>
</h3>
<%= link_to 'Back', :controller => 'rooms', :action => 'index' %>
</div>